# Generated by Django 5.0.2 on 2025-06-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_alphabet', models.JSONField()),
                ('tape_alphabet', models.JSONField()),
                ('blank_symbol', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_accepting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_symbol', models.CharField(max_length=1)),
                ('write_symbol', models.CharField(max_length=1)),
                ('move_direction', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
            ],
        ),
    ]
