# Generated by Django 5.0.2 on 2025-06-15 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='start_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_starting', to='machines.state'),
        ),
        migrations.AddField(
            model_name='transition',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='machines.state'),
        ),
        migrations.AddField(
            model_name='transition',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='transition',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='machines.state'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'machine')},
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('current_state', 'read_symbol', 'machine')},
        ),
    ]
