# Generated by Django 5.0.2 on 2025-06-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='blank_symbol',
            field=models.CharField(default='_', max_length=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='start_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_state_machines', to='machines.state'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transition',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='machines.state'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='move_direction',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Stay')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transition',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='machines.state'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('machine', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('machine', 'current_state', 'read_symbol')},
        ),
    ]
